[tool.poetry]
name = "lertarot"
version = "0.1.0"
description = ""
authors = ["Lucas Beneylton 47756391+lbeneylton@users.noreply.github.com"]
packages = [
    { include = "lertarot", from = "src" }
]
readme = "README.md"



[tool.poetry.dependencies]
python = "^3.10"
alembic = "^1.18.4"
pytest = "^9.0.3"
python-dotenv = "^1.2.2"
pyjwt = {extras = ["crypto"], version = "^2.13.0"}
python-jose = {extras = ["cryptography"], version = "^3.5.0"}


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
