"""initial migration

Revision ID: eca36e8b0785
Revises: 
Create Date: 2026-05-24 21:54:54.793013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca36e8b0785'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_status',
    sa.Column('status_id', sa.Uuid(), nullable=False),
    sa.Column('name_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('status_id', name='appointment_status_pkey'),
    sa.UniqueConstraint('name_status', name='appointment_status_name_status_key')
    )
    op.create_table('specialties',
    sa.Column('speciality_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('speciality_id', name='specialties_pkey'),
    sa.UniqueConstraint('nome', name='specialties_nome_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_index('idx_users_email_active', 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('fk_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.user_id'], name='fk_clients_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fk_user_id', name='clients_pkey')
    )
    op.create_table('readers',
    sa.Column('fk_user_id', sa.Uuid(), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.user_id'], name='fk_readers_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fk_user_id', name='readers_pkey')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fk_status_id', sa.Uuid(), nullable=False),
    sa.Column('fk_reader_id', sa.Uuid(), nullable=False),
    sa.Column('fk_client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_client_id'], ['clients.fk_user_id'], name='fk_appointment_client', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_reader_id'], ['readers.fk_user_id'], name='fk_appointment_reader', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_status_id'], ['appointment_status.status_id'], name='fk_appointment_status'),
    sa.PrimaryKeyConstraint('appointment_id', name='appointments_pkey')
    )
    op.create_index('idx_appointments_client', 'appointments', ['fk_client_id'], unique=False)
    op.create_index('idx_appointments_reader', 'appointments', ['fk_reader_id'], unique=False)
    op.create_table('reader_specialties',
    sa.Column('fk_reader_id', sa.Uuid(), nullable=False),
    sa.Column('fk_speciality_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fk_reader_id'], ['readers.fk_user_id'], name='fk_reader_specialties_1', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_speciality_id'], ['specialties.speciality_id'], name='fk_reader_specialties_2', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fk_speciality_id', 'fk_reader_id', name='reader_specialties_pkey')
    )
    op.create_table('services',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('fk_reader_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('duracao_minutes', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_reader_id'], ['readers.fk_user_id'], name='fk_service_reader', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('service_id', name='services_pkey')
    )
    op.create_index('idx_services_reader', 'services', ['fk_reader_id'], unique=False)
    op.create_table('appointment_services',
    sa.Column('fk_service_id', sa.Uuid(), nullable=False),
    sa.Column('fk_appointment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fk_appointment_id'], ['appointments.appointment_id'], name='fk_appointment_services_2', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_service_id'], ['services.service_id'], name='fk_appointment_service', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fk_service_id', 'fk_appointment_id', name='appointment_services_pkey')
    )
    op.create_index('idx_appointment_services_appointment', 'appointment_services', ['fk_appointment_id'], unique=False)
    op.create_index('idx_appointment_services_service', 'appointment_services', ['fk_service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_appointment_services_service', table_name='appointment_services')
    op.drop_index('idx_appointment_services_appointment', table_name='appointment_services')
    op.drop_table('appointment_services')
    op.drop_index('idx_services_reader', table_name='services')
    op.drop_table('services')
    op.drop_table('reader_specialties')
    op.drop_index('idx_appointments_reader', table_name='appointments')
    op.drop_index('idx_appointments_client', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('readers')
    op.drop_table('clients')
    op.drop_index('idx_users_email_active', table_name='users')
    op.drop_table('users')
    op.drop_table('specialties')
    op.drop_table('appointment_status')
    # ### end Alembic commands ###
