from typing import Protocol, Dict


class PasswordHasherContract(Protocol):
    def hash(self, password: str) -> str: ...
    def verify_hash(self, password: str, hashed_password: str) -> bool: ...


class TokenServiceContract(Protocol):
    def create_access_token(self, user_id: int, version: int) -> str: ...
    def create_refresh_token(self, user_id: int, version: int) -> str: ...
    def decode_access_token(self, token: str) -> Dict: ...
    def decode_refresh_token(self, token: str) -> Dict: ...
