"""teste alembic

Revision ID: 05038eb68a33
Revises: d7aa5f16d652
Create Date: 2026-08-22 20:47:20.781372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05038eb68a33'
down_revision: Union[str, Sequence[str], None] = 'd7aa5f16d652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery',
    sa.Column('recovery_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recovery_id')
    )
    op.create_index('uq_recovery_token_not_used', 'password_recovery', ['token_hash'], unique=True, postgresql_where=sa.text('used_at IS NULL'))
    op.drop_index(op.f('ix_codes_email_verifications_user_id'), table_name='codes_email_verifications')
    op.create_index('ix_code_email_user_id_used_at', 'codes_email_verifications', ['user_id', 'used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_code_email_user_id_used_at', table_name='codes_email_verifications')
    op.create_index(op.f('ix_codes_email_verifications_user_id'), 'codes_email_verifications', ['user_id'], unique=False)
    op.drop_index('uq_recovery_token_not_used', table_name='password_recovery', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('password_recovery')
    # ### end Alembic commands ###
