"""teste alembic

Revision ID: 0510a2df3cab
Revises: c368079165e2
Create Date: 2026-08-22 23:13:59.055319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0510a2df3cab'
down_revision: Union[str, Sequence[str], None] = 'c368079165e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_messages', 'template',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('email_messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('email_messages', 'template',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
