"""teste alembic

Revision ID: 1505a060cb1f
Revises: f5c3f5e148c1
Create Date: 2026-08-23 13:24:58.645607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1505a060cb1f'
down_revision: Union[str, Sequence[str], None] = 'f5c3f5e148c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_email_messages_processing_started_at'), 'email_messages', ['processing_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_processing_started_at'), table_name='email_messages')
    op.drop_column('email_messages', 'processing_started_at')
    # ### end Alembic commands ###
