"""Tabela Readers e Clients

Revision ID: 40a86d5f0bd6
Revises: 503c6979f803
Create Date: 2026-05-27 19:07:41.311824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a86d5f0bd6'
down_revision: Union[str, Sequence[str], None] = '503c6979f803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('readers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('user_type', sa.Enum('admin', 'reader', 'client', name='usertype', native_enum=False), nullable=False))
    op.drop_column('users', 'senha_hash')
    op.drop_column('users', 'type')
    op.drop_column('users', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('senha_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'name')
    op.drop_table('readers')
    op.drop_table('clients')
    # ### end Alembic commands ###
