"""teste alembic

Revision ID: c368079165e2
Revises: f52a648d9d25
Create Date: 2026-08-22 23:09:51.472790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c368079165e2'
down_revision: Union[str, Sequence[str], None] = 'f52a648d9d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('variables', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'variables')
    # ### end Alembic commands ###
