"""teste alembic

Revision ID: cccdfac36d53
Revises: 720cf1b9bf13
Create Date: 2026-08-20 20:28:48.864400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cccdfac36d53'
down_revision: Union[str, Sequence[str], None] = '720cf1b9bf13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes_email_verifications',
    sa.Column('code_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_codes_email_verifications_user_id'), 'codes_email_verifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_email_active'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_users_username_active'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.create_index('uq_users_email_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_users_username_active', 'users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_username_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_users_username_active'), 'users', ['username'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_users_email_active'), 'users', ['email'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_codes_email_verifications_user_id'), table_name='codes_email_verifications')
    op.drop_table('codes_email_verifications')
    # ### end Alembic commands ###
