"""create email_messages table

Revision ID: d7aa5f16d652
Revises: cccdfac36d53
Create Date: 2026-08-22 18:09:33.271807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7aa5f16d652'
down_revision: Union[str, Sequence[str], None] = 'cccdfac36d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('message_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('to', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'RETRY', 'FAILED', name='message_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_email_messages_idempotency_key'), 'email_messages', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_email_messages_status'), 'email_messages', ['status'], unique=False)
    op.create_index(op.f('ix_email_messages_template'), 'email_messages', ['template'], unique=False)
    op.create_index(op.f('ix_email_messages_to'), 'email_messages', ['to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_to'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_template'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_status'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_idempotency_key'), table_name='email_messages')
    op.drop_table('email_messages')
    # ### end Alembic commands ###
