"""teste alembic

Revision ID: f52a648d9d25
Revises: 05038eb68a33
Create Date: 2026-08-22 20:51:48.721613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52a648d9d25'
down_revision: Union[str, Sequence[str], None] = '05038eb68a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('catalogs_user_id_fkey'), 'catalogs', type_='foreignkey')
    op.create_foreign_key(None, 'catalogs', 'readers', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogs', type_='foreignkey')
    op.create_foreign_key(op.f('catalogs_user_id_fkey'), 'catalogs', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
