"""teste alembic

Revision ID: f5c3f5e148c1
Revises: 0510a2df3cab
Create Date: 2026-08-23 01:59:03.253711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c3f5e148c1'
down_revision: Union[str, Sequence[str], None] = '0510a2df3cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_email_messages_template'), table_name='email_messages')
    op.drop_column('email_messages', 'template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('template', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_email_messages_template'), 'email_messages', ['template'], unique=False)
    op.alter_column('email_messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
