from typing import Any, Protocol


class ScalarResultContract(Protocol):
    def all(self) -> list[Any]: ...
        
    def first(self) -> Any | None: ...


class QueryResultContract(Protocol):
    def scalars(self) -> ScalarResultContract: ...

    def scalar_one_or_none(self) -> Any | None: ...

    def rowcount(self) -> int: ...


class StatementContract(Protocol):
    def where(self, *criteria: Any) -> "StatementContract": ...

    def values(self, **values: Any) -> "StatementContract": ...


class SessionContract(Protocol):
    def __call__(self) -> "SessionContract": ...

    def add(self, *args: Any, **kwargs: Any) -> None: ...

    def execute(self, statement: Any, *args: Any, **kwargs: Any) -> QueryResultContract:
        ...

    def close(self) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
        
    def flush(self) -> None: ...
        
    def refresh(self, instance: object) -> None: ...
    
    
    def update(self): ...